USE [GO_TRANSPORT]
GO

SET IDENTITY_INSERT [dbo].[APP_ROLE] ON 

INSERT [dbo].[APP_ROLE] ([ROLE_ID], [NAME], [NORMALIZED_NAME], [CONCURRENCY_STAMP], [IS_ACTIVE], [CREATED_AT], [UPDATED_AT], [CREATION_USER], [UPDATE_USER]) VALUES (1, 'Administrador', 'ADMINISTRADOR', NEWID(), 1, GETDATE(), GETDATE(), 'SYSTEM', 'SYSTEM')
INSERT [dbo].[APP_ROLE] ([ROLE_ID], [NAME], [NORMALIZED_NAME], [CONCURRENCY_STAMP], [IS_ACTIVE], [CREATED_AT], [UPDATED_AT], [CREATION_USER], [UPDATE_USER]) VALUES (2, 'Operario', 'OPERARIO', NEWID(), 1, GETDATE(), GETDATE(), 'SYSTEM', 'SYSTEM')

SET IDENTITY_INSERT [dbo].[APP_ROLE] OFF
GO

SET IDENTITY_INSERT [dbo].[BAS_IDENTIFICATION_TYPE] ON 

INSERT [dbo].[BAS_IDENTIFICATION_TYPE] ([IDENTIFICATION_TYPE_ID], [DESCRIPTION], [IS_ACTIVE], [CREATED_AT], [UPDATED_AT], [CREATION_USER], [UPDATE_USER]) VALUES (1, 'Cédula de ciudadanía', 1, GETDATE(), GETDATE(), 'SYSTEM', 'SYSTEM')
INSERT [dbo].[BAS_IDENTIFICATION_TYPE] ([IDENTIFICATION_TYPE_ID], [DESCRIPTION], [IS_ACTIVE], [CREATED_AT], [UPDATED_AT], [CREATION_USER], [UPDATE_USER]) VALUES (2, 'Cédula de extranjería', 1, GETDATE(), GETDATE(), 'SYSTEM', 'SYSTEM')
INSERT [dbo].[BAS_IDENTIFICATION_TYPE] ([IDENTIFICATION_TYPE_ID], [DESCRIPTION], [IS_ACTIVE], [CREATED_AT], [UPDATED_AT], [CREATION_USER], [UPDATE_USER]) VALUES (3, 'Pasaporte', 1, GETDATE(), GETDATE(), 'SYSTEM', 'SYSTEM')

SET IDENTITY_INSERT [dbo].[BAS_IDENTIFICATION_TYPE] OFF
GO

SET IDENTITY_INSERT [dbo].[BAS_MANUFACTURER] ON 

INSERT [dbo].[BAS_MANUFACTURER] ([MANUFACTURER_ID], [DESCRIPTION], [IS_ACTIVE], [CREATED_AT], [UPDATED_AT], [CREATION_USER], [UPDATE_USER]) VALUES (1, 'SCANIA', 1, GETDATE(), GETDATE(), 'SYSTEM', 'SYSTEM')
INSERT [dbo].[BAS_MANUFACTURER] ([MANUFACTURER_ID], [DESCRIPTION], [IS_ACTIVE], [CREATED_AT], [UPDATED_AT], [CREATION_USER], [UPDATE_USER]) VALUES (2, 'CHEVROLET', 1, GETDATE(), GETDATE(), 'SYSTEM', 'SYSTEM')
INSERT [dbo].[BAS_MANUFACTURER] ([MANUFACTURER_ID], [DESCRIPTION], [IS_ACTIVE], [CREATED_AT], [UPDATED_AT], [CREATION_USER], [UPDATE_USER]) VALUES (3, 'VOLVO', 1, GETDATE(), GETDATE(), 'SYSTEM', 'SYSTEM')
INSERT [dbo].[BAS_MANUFACTURER] ([MANUFACTURER_ID], [DESCRIPTION], [IS_ACTIVE], [CREATED_AT], [UPDATED_AT], [CREATION_USER], [UPDATE_USER]) VALUES (4, 'MERCEDES BENZ', 1, GETDATE(), GETDATE(), 'SYSTEM', 'SYSTEM')
INSERT [dbo].[BAS_MANUFACTURER] ([MANUFACTURER_ID], [DESCRIPTION], [IS_ACTIVE], [CREATED_AT], [UPDATED_AT], [CREATION_USER], [UPDATE_USER]) VALUES (5, 'HINO', 1, GETDATE(), GETDATE(), 'SYSTEM', 'SYSTEM')
INSERT [dbo].[BAS_MANUFACTURER] ([MANUFACTURER_ID], [DESCRIPTION], [IS_ACTIVE], [CREATED_AT], [UPDATED_AT], [CREATION_USER], [UPDATE_USER]) VALUES (6, 'YUTONG', 1, GETDATE(), GETDATE(), 'SYSTEM', 'SYSTEM')
INSERT [dbo].[BAS_MANUFACTURER] ([MANUFACTURER_ID], [DESCRIPTION], [IS_ACTIVE], [CREATED_AT], [UPDATED_AT], [CREATION_USER], [UPDATE_USER]) VALUES (7, 'BYD', 1, GETDATE(), GETDATE(), 'SYSTEM', 'SYSTEM')
INSERT [dbo].[BAS_MANUFACTURER] ([MANUFACTURER_ID], [DESCRIPTION], [IS_ACTIVE], [CREATED_AT], [UPDATED_AT], [CREATION_USER], [UPDATE_USER]) VALUES (8, 'FORD', 1, GETDATE(), GETDATE(), 'SYSTEM', 'SYSTEM')

SET IDENTITY_INSERT [dbo].[BAS_MANUFACTURER] OFF
GO

SET IDENTITY_INSERT [dbo].[APP_USER] ON 
GO
INSERT [dbo].[APP_USER] ([USER_ID], [FIRST_NAME], [LAST_NAME], [USERNAME], [NORMALIZED_USERNAME], [EMAIL], [NORMALIZED_EMAIL], [EMAIL_CONFIRMED], [PASSWORD_HASH], [SECURITY_STAMP], [CONCURRENCY_STAMP], [PHONE_NUMBER], [PHONE_NUMBER_CONFIRMED], [TWO_FACTOR_ENABLED], [LOCKOUT_END], [LOCKOUT_ENABLED], [ACCESS_FAILED_COUNT], [IS_ACTIVE], [CREATED_AT], [UPDATED_AT], [CREATION_USER], [UPDATE_USER]) VALUES (1, N'Administrador', N'Go Transport', N'admin@goTransport.com', N'ADMIN@GOTRANSPORT.COM', N'admin@goTransport.com', N'ADMIN@GOTRANSPORT.COM', 0, N'AQAAAAEAACcQAAAAEPDPZ8M2zH/2OgVnb10gA1aquUUMqJ4lssVqsFBpjnbbvi/CqwCjpsGVFBiHEPfJAA==', N'MNJSDEZVKTKDU3RVVJN72UBRYQRBO6QB', N'f7c378c5-cd25-4411-b5b0-3d8db53fde5e', NULL, 0, 0, NULL, 1, 0, 1, GETDATE(), GETDATE(), 'SYSTEM', 'SYSTEM')
GO
SET IDENTITY_INSERT [dbo].[APP_USER] OFF
GO
INSERT [dbo].[APP_USER_ROLE] ([USER_ID], [ROLE_ID], [IS_ACTIVE], [CREATED_AT], [UPDATED_AT], [CREATION_USER], [UPDATE_USER]) VALUES (1, 1, 1, GETDATE(), GETDATE(), 'SYSTEM', 'SYSTEM')
GO